vkusnosam/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from config import settings
from recipes.views import page_permission_denied

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

handler403 = page_permission_denied

vkusnosam/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from django.urls import path, reverse_lazy

from .views import CustomLoginView, RegisterView, ProfileView, UserPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # Изменение и сброс пароля
    path('password-change/', UserPasswordChangeView.as_view(), name='password-change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password/password-change-done.html'), name='password-change-done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password/password-reset-form.html',
        email_template_name="users/password/password_reset_email.html",
        success_url = reverse_lazy('users:password_reset_done')),
        name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password/password-reset-done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password/password_reset_confirm.html",
             success_url = reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password/password_reset_complete.html"),
         name='password_reset_complete'),

]

vkusnosam/templates/base.html
{% load static %}
{% load recipe_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link type="text/css" href="{% static 'recipes/css/styles.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'recipes/css/normalize.css' %}" rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'recipes/images/favicon.ico' %}" type="image/x-icon"/>

</head>
<body>
    <!-- блок хедер -->
    <header class="page-header">
    <a href="{% url 'home' %}">
        <img src="/media/default_images/logo.png" title="Главная страница сайта"
             alt="Логотип сайта" class="logo">
    </a>

    <div class="site-name">ВкусноСам</div>
    <div class="deviz">Ищи, делись, готовь!</div>

    <!-- Отображение сообщений -->
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <!--     Блок навигации    -->
    <nav class="nav-block">
        {% if user.is_authenticated %}
            <p><a href="{% url 'users:profile' %}" class="username" data-tooltip="Детальная информация о пользователе">Профиль {{user.username}}</a></p>
            <!--   Форма для выхода из аккаунта     -->
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="exit">Выйти</button>
            </form>

        {% else %}
            <p><a href="{% url 'users:login' %}">Авторизация</a></p>
            <p><a href="{% url 'users:register' %}">Регистрация</a></p>
            <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
        {% endif %}
        {% if user.is_superuser %}
            <a href=" {% url 'admin:index' %}" class="admin">Админка</a>
        {% endif %}
    </nav>
    </header>
    <!-- конец блока хедер -->

<!-- Блок контента-->
<main class="content">
    {% block content %}
    {% endblock %}
</main>

{% block navigation %}
{% endblock %}

<!--Конец блока контента-->

<!--Футер-->
<footer>
   <div id="footer">
		<p class="footer-text">&copy; Все права на материалы, находящиеся на сайте www.VkusnoSam.com, охраняются в соответствии с действующим законодательством. При любом использовании материалов сайта
, гиперссылка (hyperlink) на www.VkusnoSam.com обязательна. Администрация сайта не несет ответственности за результат применения приведенных кулинарных рецептов, методик их приготовления,
кулинарных и прочих рекомендаций, работоспособность ресурсов, на которые размещены гиперссылки, и за содержание рекламных объявлений. Администрация сайта может не разделять мнения авторов статей,
размещённых на сайте www.VkusnoSam.com e-mail info@VkusnoSam.com.</p>
	</div>
</footer>
<!--конец футера и страницы-->
</body>
<script type="text/javascript" src='{% static "recipes/js/forSite.js" %}'></script>
</html>