vkusnosam/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from config import settings
from recipes.views import page_permission_denied

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('users/', include('users.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

handler403 = page_permission_denied

vkusnosam/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView

from django.urls import path, reverse_lazy

from .views import CustomLoginView, RegisterView, ProfileView, UserPasswordChangeView

app_name = 'users'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),

    # Изменение и сброс пароля
    path('password-change/', UserPasswordChangeView.as_view(), name='password-change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password/password-change-done.html'), name='password-change-done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password/password-reset-form.html',
        email_template_name="users/password/password_reset_email.html",
        success_url = reverse_lazy('users:password_reset_done')),
        name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password/password-reset-done.html'), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="users/password/password_reset_confirm.html",
             success_url = reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),

    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password/password_reset_complete.html"),
         name='password_reset_complete'),

]

vkusnosam/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    """
    Класс для расширения стандартной модели user
    """
    avatar = models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d', verbose_name='Аватар')
    age = models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')
    interests = models.TextField(blank=True, null=True, verbose_name='Интересы')

vkusnosam/users/forms.py
from django import forms
from django.contrib.auth import get_user_model

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class UserLoginForm(AuthenticationForm):
    """
    Класс для отображения полей формы login.
    Используется для аутентификации пользователя.
    """
    username = forms.CharField(max_length=150, label="Логин")
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']



class UserRegisterForm(UserCreationForm):
    """
    Модель для регистрации нового пользователя
    """
    username = forms.CharField(max_length=150, label="Логин")
    password1 = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    password2 = forms.CharField(widget=forms.PasswordInput, label="Повторите пароль")

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name',
                  'password1', 'password2']
        labels = {
            'email': "E-mail",
            'first_name': "Имя",
            'last_name': "Фамилия"
        }

    def clean_email(self) -> dict:
        """
        Метод проверяет базу существует-ли похожая почта
        :return: dict
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует")
        return email


class Profile(forms.ModelForm):
    """
    Модель для профайла пользователя.
    """
    username = forms.CharField(disabled=True, label="Логин")
    email = forms.CharField(disabled=True, label="E-mail")

    class Meta:
        model = get_user_model()
        fields = ['username', 'avatar', 'age', 'interests', 'email', 'first_name', 'last_name',]
        labels = {
            'avatar': "Аватарка",
            'first_name': "Имя",
            'last_name': "Фамилия",
            'age': "Возраст",
            'interests': "Интересы"
        }


class UserPasswordChangeForm(PasswordChangeForm):
    """
    Форма для сброса старого пароля и создание нового
    """
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={"class": 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={"class": 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение нового пароля",
                                    widget=forms.PasswordInput(attrs={"class": 'form-input'}))

vkusnosam/users/views.py
from http.client import responses
from typing import Dict

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.utils.translation import gettext as _


from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import UserLoginForm, UserRegisterForm, Profile, UserPasswordChangeForm

from recipes.models import Recipe, Comment


class CustomLoginView(LoginView):
    """
    Представление для авторизации пользователя
    """
    authentication_form = UserLoginForm
    template_name = 'users/login_form.html'
    extra_context = {'title': 'Авторизация'}
    success_url = 'home'


    def get_success_url(self) -> str:
        """
        Метод для переадресации суперпользователя в админ панель
        :return: str (URL для перенаправления)
        """
        if self.request.user.is_superuser:
            return reverse_lazy('admin:index') # возвращает '/admin'
        return super().get_success_url() # возвращает '/home'


    def form_valid(self, form: any) -> str:
        """
        Выводит сообщение об успешной авторизации если данные формы валидны
        :param form: form
        :return: str
        """
        response = super().form_valid(form)
        messages.success(self.request, _("Добро пожаловать! Вы успешно авторизовались в системе!"))
        return response

    def form_invalid(self, form: any) -> str:
        """
        Выводит сообщение об ошибке авторизации если данные формы не валидны
        :param form: form
        :return: str
        """
        response = super().form_invalid(form)
        messages.error(self.request, _("Ошибка! Неверно введен логин или пароль! Попробуйте еще раз!"))
        return super().form_invalid(form)



class RegisterView(CreateView):
    """
    Представление для создания нового пользователя
    """
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    extra_context = {
        'title': "Регистрация нового пользователя",
    }


class ProfileView(UpdateView):
    """
    Представление для отображения и обновления профиля пользователя.
    """
    model = get_user_model()
    form_class = Profile
    success_url = reverse_lazy('users:profile')
    template_name = 'users/profile.html'

    def get_object(self, queryset=None):
        """
        Метод для получения текущего юзера из базы.
        Возвращает текущего аутентифицированного пользователя.
        :param queryset: None
        :return:
        """
        return self.request.user

    def get_context_data(self, **kwargs) -> Dict:
        """
        Метод для получения связанных данных. Получает все рецепты опубликованные пользователем.
        :param kwargs:
        :return: Dict
        """
        context = super().get_context_data(**kwargs)
        users_recipes = Recipe.objects.filter(user=self.request.user)
        users_comments = Comment.objects.filter(user=self.request.user)
        context['users_recipes'] = users_recipes
        context['users_comments'] = users_comments
        return context

    def form_valid(self, form: any) -> str:
        """
        Выводит сообщение об успешном обновлении профиля пользователя если форма валидна.
        :param form: form
        :return: str
        """
        response = super().form_valid(form)
        messages.success(self.request, _("Вы успешно обновили свой профиль!"))
        return response

    def form_invalid(self, form: any) -> str:
        """
        Выводит сообщение об ошибке если форма не валидна.
        :param form: Any
        :return: str
        """
        response = super().form_invalid(form)
        messages.error(self.request, _("Ошибка! Попробуйте еще раз!"))
        return super().form_invalid(form)


class UserPasswordChangeView(PasswordChangeView):
    """
    Представление для смены старого пароля на новый
    """
    form_class = UserPasswordChangeForm
    template_name = 'users/password/password-change-form.html'
    success_url = reverse_lazy('users:password-change-done')
    extra_context = {
        'title': "Смена пароля"
    }

vkusnosam/users/templates/users/password/password-change-done.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

vkusnosam/users/templates/users/password/password-change-form.html
{% extends 'base.html' %}

{% block content %}

<h1>Изменение пароля</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

vkusnosam/users/templates/users/password/password-reset-done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>
<p >{% translate 'We’ve emailed you instructions for setting your password,
    if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure
    you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

vkusnosam/users/templates/users/password/password-reset-form.html
{% extends 'base.html' %}

{% block content %}

<h1>Восстановление пароля!</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Сбросить по почте</button></p>
</form>

{% endblock %}

vkusnosam/users/templates/users/password/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
 
{% endblock %}

vkusnosam/users/templates/users/password/password_reset_confirm.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Новый пароль</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>
 
{% endblock %}

vkusnosam/users/templates/users/password/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}